### ISSUE TITLE
Error compiling program for HoodLoader2 Uno

### ISSUE THREAD

**Issue by Sanjeet990** [NicoHood/HoodLoader2#124]
I was able to flash HoodLoader2 correctly. I can also veryfy this in devices and printers but while flashing any program, I'm getting this:

cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.
cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.
cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.
cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.
cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.
cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.
cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.

exit status 1

Compilation error: exit status 1

**Comment by Bnco3DTech** [comment]
Did you fix it I have same issue.

cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.

**Comment by Kandermann** [comment]
I am having this issue too!
kind of wierd

**Comment by TannerGilbert** [comment]
I also got the same error when using Arduino IDE 2.x. Using Arduino IDE 1.8.x instead solved the problem for me. (PS Thanks @FRALEXAlexander for the advice)

**Comment by DRSDavidSoft** [comment]
@NicoHood Same issue with VS Code and the Arduino extension :(

<img width="559" alt="image" src="https://github.com/NicoHood/HoodLoader2/assets/4673812/1c736024-b207-4e7f-820e-b6f24f4fb0ab">

**Comment by syfenx** [comment]
pretty sure I fixed this by installing 1.8.3 Arduino AVR Boards in board manager

**Comment by SlopeSlayer910** [comment]
> Using Arduino IDE 1.8.x instead solved the problem for me.

I am also encountering this error. Switching to Arduino IDE 1.8.19 solved the problem for me as well however compatibility with Arduino IDE 2.X.X would be greatly appreciated.

**Comment by Sanjeet990** [comment]
The issue above fixes by installing the proper board definitions in board manager. Closing it to prevent any confusion.

**Comment by DRSDavidSoft** [comment]
@Sanjeet990 Are you saying that the issue will not occur with Arduino 2.X as well? It was established that the legacy IDE doesn't have this issue anymore.

Also I use VS Code with the [Arduino extension by Microsoft](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino) which caused the error I posted.

For building the HoodLoader I would prefer not to **need** the legacy IDE since everyone is switching away from it to the new, modular, cool v2.x IDE. Would you please re-open the issue until this is also fixed for the v2.x?
