### ISSUE TITLE
Serial1 buffer size

### ISSUE THREAD

**Issue by supersjimmie** [NicoHood/HoodLoader2#49]
My test code is:
```
void loop() {
  if (Serial1.available()) {
      delay(5000);
      while(Serial1.available()) {
        Keyboard.write(Serial1.read());
      }
  }
}
```
I am sending 40 counting bytes, like 1234567890123456789012345678901234567890
I expected all 40 bytes to be buffered during the delay(5000) and then retrieved.
But the result is only:
```
123456789012345
```

Edit: In addition, I noticed that I needed to send my bytes slowly into Serial1, I had to add a `delay(2)` between each byte at the sender. (Sender is just another arduino style board)

**Comment by NicoHood** [comment]
This is not an issue of Hoodloader2, but an issue of the arduino code. In this particular case the Serial buffer is 16 (because of MCU limitations). You need to do a block read instead of a single byte read. This issue is expected and the error is caused by your code. See USB Serial Bridge for an example of faster Serial read.
